### ISSUE TITLE
Это перечисление выглядит ужасно

### ISSUE THREAD

**Issue by pomponchik** [ggwmwgg/tgbot#10]
https://github.com/ggwmwgg/tgbot/blob/aa32fff0b78780b4910b9f2bc92eedc991eb8875/handlers/errors/error_handler.py#L34

Попробуйте придумать способ написать то же самое более компактно и без такого числа дублей.

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto
