### ISSUE TITLE
Используйте модуль logging или ему подобные

### ISSUE THREAD

**Issue by pomponchik** [ggwmwgg/tgbot#2]
https://github.com/ggwmwgg/tgbot/blob/aa32fff0b78780b4910b9f2bc92eedc991eb8875/app.py#L18

Также вы можете использовать библиотеку [polog](https://github.com/pomponchik/polog).

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto , тут я использую логгинг
