### ISSUE TITLE
getenv и так возвращает строки, зачем конвертация?

### ISSUE THREAD

**Issue by pomponchik** [ggwmwgg/tgbot#3]
https://github.com/ggwmwgg/tgbot/blob/aa32fff0b78780b4910b9f2bc92eedc991eb8875/data/config.py#L10C33-L10C33

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto
