### ISSUE TITLE
Повторяющийся код

### ISSUE THREAD

**Issue by pomponchik** [ggwmwgg/tgbot#4]
https://github.com/ggwmwgg/tgbot/blob/aa32fff0b78780b4910b9f2bc92eedc991eb8875/handlers/users/start.py#L63

Данная строчка повторяется для всех вариантов в условии. Почему бы ее не вынести из блока условий вообще?

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto
