### ISSUE TITLE
А если у пользователя выбран узбекский язык?

### ISSUE THREAD

**Issue by pomponchik** [ggwmwgg/tgbot#6]
https://github.com/ggwmwgg/tgbot/blob/aa32fff0b78780b4910b9f2bc92eedc991eb8875/handlers/users/start.py#L125

В этом случае он тоже увидит сообщение на русском о том, что он выбрал узбекский?

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto
