### ISSUE TITLE
Обычно это указывают иначе

### ISSUE THREAD

**Issue by pomponchik** [ggwmwgg/tgbot#7]
https://github.com/ggwmwgg/tgbot/blob/aa32fff0b78780b4910b9f2bc92eedc991eb8875/handlers/users/start.py#L109

По вашей записи пользователь не отличит обязательную часть номера ("+998" в данном случае) от переменной. Чтобы это было визуально понятно, часто пишут вот в таком формате: "+998ХХХХХХХХХ".

И кстати, если пользователь выбрал русский или английский язык, у него с высокой вероятностью будет номер соответствующей страны. Вы уверены, что не хотите пропустить его?

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto
