### ISSUE TITLE
Это запрос персональных данных

### ISSUE THREAD

**Issue by pomponchik** [ggwmwgg/tgbot#8]
https://github.com/ggwmwgg/tgbot/blob/aa32fff0b78780b4910b9f2bc92eedc991eb8875/handlers/users/start.py#L103

Учитывайте, что во многих странах (включая Россию) сбор персональных данных сопровождается особыми правилами законодательства. Пользователь должен явно указать, на что он дает согласие в данном случае. Также он должен иметь возможность отозвать это согласие, с последующим удалением данных из вашей БД.

**Comment by ggwmwgg** [comment]
Здравствуйте, это мой самый первый проект, не судите строго, сейчас закончил разработку нового, очень жду Вашего ревью =) https://github.com/ggwmwgg/tg_seller_crypto , в нынешнем проекте персональные данные не собираются, всё анонимно
